jobs:

  - name: test_release
    type: release
    steps:
      - IN: test_ship_ver
      - IN: plv2withscript_runsh
      - TASK: managed
        bump: minor
  
  #- name: test_releasedel
  #  type: release
  #  steps:
   #   - IN: test_ship_ver
    #  - TASK: managed
     #   bump: minor
        
  - name: plv2withscript_runsh
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: test_same_repo1
      #- IN: t1
      - TASK:
        - script: IN/test_same_repo1/gitRepo/echo.sh 
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed' 
    
    
  - name: build_cli
    type: runCLI
    allowPublicAccess: true
    steps:
      - IN: plv2withscript_runsh
      - IN: test_same_repo1
      - IN: test_ship_dh_cli
      - TASK:
        - script: IN/test_same_repo1/gitRepo/echo.sh 
      - OUT: sample_out_img
   
   #allowPublicAccess: true
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'   

  - name: test_manifest_dep123
    type: manifest
    steps:
      - IN: test_deploy_img  
      - IN: t1
   # allowPublicAccess: true
      
  #- name: test_deploy_ddc
   # type: deploy
   # steps:
    #  - IN: test_manifest_dep
    #  - IN: test_ddc_cluster
    #  - IN: test_ddc_dopts
    #  - TASK: managed     
    
    